// =============================================================================
// tb_fpnew_wrapper.sv — Self-checking testbench for the fpnew_wrapper FU
// =============================================================================
//
// fpnew_wrapper evaluates one single-precision FPU operation for all N_THREADS
// threads and streams the results out with a valid/ready handshake. This
// testbench drives the input valid/ready interface, drains the output interface,
// and checks every emitted result against hard-coded golden data generated by
// asm-kernels/gen_fpnew_vectors.py (IEEE-754 binary32 semantics; FMA is fused).
//
// Results are matched to operations by op_tag_o.op_id, so the testbench is
// independent of the FPU latency (the current implementation is combinational;
// div/sqrt are multi-cycle).
//
// Notes:
//   * fpnew_pkg.sv must be compiled in and `tb/` must be on the include path
//     (for fpnew_vectors.svh).
//   * Verilator needs --no-assert-case: the DUT uses `unique case` over enum
//     literals that include 'x.
//   * fpnew's in_ready_o only asserts while in_valid_i is high, so the driver
//     always asserts valid first and then waits for ready.
// =============================================================================

`timescale 1ns/1ps
`default_nettype none

module tb_fpnew_wrapper;
    import params_pkg::*;
    import control_unit_pkg::*;
    import fpnew_pkg::*;
    import tb_config_pkg::RST_CYCLES;

    localparam int FPU_WIDTH = N_THREADS * RLEN;
    typedef logic [N_THREADS-1:0][RLEN-1:0] fpu_regs_t;

    // Hard-coded golden operands and expected results.
    `include "fpnew_vectors.svh"

    // -----------------------------------------------------------------------
    // Clock / reset
    // -----------------------------------------------------------------------
    logic clk = 0;
    always #5 clk = ~clk;
    logic rst_n = 0;

    // -----------------------------------------------------------------------
    // DUT
    // -----------------------------------------------------------------------
    logic in_valid, in_ready;
    logic out_valid, out_ready;
    op_tag_s tag_i, tag_o;
    instr_s instr;
    fpu_regs_t rs1, rs2, rs3;
    logic [FPU_WIDTH-1:0] result_o;
    fpnew_pkg::status_t [N_THREADS-1:0] status_o;

    fpnew_wrapper dut (
        .clk(clk), .rst_n(rst_n),
        .in_valid_i(in_valid), .in_ready_o(in_ready),
        .out_valid_o(out_valid), .out_ready_i(out_ready),
        .op_tag_i(tag_i), .instr_i(instr),
        .rs1_data_i(rs1), .rs2_data_i(rs2), .rs3_data_i(rs3),
        .op_tag_o(tag_o), .result_o(result_o), .status_o(status_o)
    );

    // -----------------------------------------------------------------------
    // Op table: index -> {fpnew op, op_mod, rnd/subop, operand selects}.
    // Matches gen_fpnew_vectors.py OPS and control_unit.sv.
    // -----------------------------------------------------------------------
    function automatic instr_s make_instr(input int unsigned op);
        instr_s i;
        i = '0;
        case (op)
            0:  begin i.fpu_opcode=ADD;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op1_sel=FPU_OP1_SEL_RS1; i.fpu_op2_sel=FPU_OP2_SEL_RS2; end
            1:  begin i.fpu_opcode=ADD;      i.fpu_op_modifier=1'b1; i.fpu_roundmode=3'b000; i.fpu_op1_sel=FPU_OP1_SEL_RS1; i.fpu_op2_sel=FPU_OP2_SEL_RS2; end
            2:  begin i.fpu_opcode=MUL;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            3:  begin i.fpu_opcode=DIV;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            4:  begin i.fpu_opcode=SQRT;     i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            5:  begin i.fpu_opcode=MINMAX;   i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            6:  begin i.fpu_opcode=MINMAX;   i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b001; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            7:  begin i.fpu_opcode=SGNJ;     i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            8:  begin i.fpu_opcode=SGNJ;     i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b001; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            9:  begin i.fpu_opcode=SGNJ;     i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b010; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            10: begin i.fpu_opcode=CMP;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b001; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            11: begin i.fpu_opcode=CMP;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            12: begin i.fpu_opcode=CMP;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b010; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; end
            13: begin i.fpu_opcode=CLASSIFY; i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            14: begin i.fpu_opcode=F2I;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            15: begin i.fpu_opcode=F2I;      i.fpu_op_modifier=1'b1; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            16: begin i.fpu_opcode=I2F;      i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            17: begin i.fpu_opcode=I2F;      i.fpu_op_modifier=1'b1; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; end
            18: begin i.fpu_opcode=FMADD;    i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; i.fpu_op2_sel=FPU_OP2_SEL_RS3; end
            19: begin i.fpu_opcode=FMADD;    i.fpu_op_modifier=1'b1; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; i.fpu_op2_sel=FPU_OP2_SEL_RS3; end
            20: begin i.fpu_opcode=FNMSUB;   i.fpu_op_modifier=1'b0; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; i.fpu_op2_sel=FPU_OP2_SEL_RS3; end
            21: begin i.fpu_opcode=FNMSUB;   i.fpu_op_modifier=1'b1; i.fpu_roundmode=3'b000; i.fpu_op0_sel=FPU_OP0_SEL_RS1; i.fpu_op1_sel=FPU_OP1_SEL_RS2; i.fpu_op2_sel=FPU_OP2_SEL_RS3; end
            default: ;
        endcase
        return i;
    endfunction

    // -----------------------------------------------------------------------
    // Scoreboard
    // -----------------------------------------------------------------------
    typedef struct {
        op_tag_s              tag;
        logic [FPU_WIDTH-1:0] exp;
        bit                   chk_stat;
        fpnew_pkg::status_t   exp_stat;
    } scb_t;

    scb_t scb[$];
    int n_sent, n_recv, n_errors, n_printed;
    logic [W_OP_ID-1:0] next_id;

    task automatic report_error(input string msg);
        n_errors++;
        if (n_printed < 16) begin
            $display("  [FAIL] t=%0t %s", $time, msg);
            n_printed++;
        end
    endtask

    // Result monitor: matches output beats to scoreboard entries by op_id.
    always @(posedge clk) begin
        if (rst_n && out_valid && out_ready) begin
            logic [FPU_WIDTH-1:0] got;
            op_tag_s             gtag;
            int                  idx;
            got  = result_o;
            gtag = tag_o;
            n_recv++;
            idx = -1;
            for (int i = 0; i < scb.size(); i++)
                if (scb[i].tag.op_id === gtag.op_id) begin idx = i; break; end
            if (idx < 0) begin
                report_error($sformatf("output beat with unknown tag op_id=%0d", gtag.op_id));
            end else begin
                if (got !== scb[idx].exp)
                    report_error($sformatf("op_id=%0d result mismatch: got %h want %h",
                                           gtag.op_id, got, scb[idx].exp));
                if (gtag !== scb[idx].tag)
                    report_error($sformatf("op_id=%0d tag passthrough mismatch", gtag.op_id));
                if (scb[idx].chk_stat)
                    for (int l = 0; l < N_THREADS; l++)
                        if (status_o[l] !== scb[idx].exp_stat)
                            report_error($sformatf("op_id=%0d lane%0d status got %b want %b",
                                                   gtag.op_id, l, status_o[l], scb[idx].exp_stat));
                scb.delete(idx);
            end
        end
    end

    // -----------------------------------------------------------------------
    // Driver
    // -----------------------------------------------------------------------
    // Core transaction: assert valid with the given operands and hold it until
    // accepted; optionally toggle out_ready_i while stalled (back-pressure).
    task automatic drive(input instr_s ins,
                         input logic [FPU_WIDTH-1:0] a,
                         input logic [FPU_WIDTH-1:0] b,
                         input logic [FPU_WIDTH-1:0] c,
                         input logic [FPU_WIDTH-1:0] exp,
                         input bit chk_stat,
                         input fpnew_pkg::status_t exp_stat,
                         input bit rand_ready);
        op_tag_s t;
        @(negedge clk);
        instr = ins;
        rs1 = fpu_regs_t'(a);
        rs2 = fpu_regs_t'(b);
        rs3 = fpu_regs_t'(c);
        t = '0;
        t.op_id = next_id;
        t.instr = ins;
        tag_i = t;
        in_valid = 1'b1;
        begin
            scb_t e;
            e.tag = t;
            e.exp = exp;
            e.chk_stat = chk_stat;
            e.exp_stat = exp_stat;
            scb.push_back(e);
        end
        n_sent++;
        next_id++;
        #1;
        while (!in_ready) begin
            @(negedge clk);
            if (rand_ready)
                out_ready = ($urandom_range(0, 1) != 0);
            #1;
        end
        out_ready = 1'b1;
        @(posedge clk); #1;          // accepted here
        @(negedge clk);
        in_valid = 1'b0;
        #1;
    endtask

    task automatic issue(input int unsigned op, input int unsigned tx, input bit rand_ready);
        drive(make_instr(op), FPU_VEC_A[op][tx], FPU_VEC_B[op][tx], FPU_VEC_C[op][tx],
              FPU_VEC_R[op][tx], 1'b0, 5'b0, rand_ready);
    endtask

    // Drain until every issued transaction has come back.
    task automatic drain(input int max_cycles);
        int cycles;
        out_ready = 1'b1;
        cycles = 0;
        while ((scb.size() != 0) && (cycles < max_cycles)) begin
            @(posedge clk);
            #1;
            cycles++;
        end
        if (scb.size() != 0)
            report_error($sformatf("%0d issued transaction(s) never came back (stuck)",
                                   scb.size()));
    endtask

    // -----------------------------------------------------------------------
    // Stimulus
    // -----------------------------------------------------------------------
    initial begin
        repeat (40000) @(posedge clk);
        $fatal(1, "global watchdog expired");
    end

    int unsigned rand_op;
    initial begin
        in_valid = 0; out_ready = 0;
        instr = '0; tag_i = '0;
        rs1 = '0; rs2 = '0; rs3 = '0;
        n_sent = 0; n_recv = 0; n_errors = 0; n_printed = 0;
        next_id = 0;

        rst_n = 1'b0;
        repeat (RST_CYCLES) @(posedge clk);
        @(negedge clk);
        rst_n = 1'b1;
        @(negedge clk); #1;

        // -------------------------------------------------------------------
        // TEST 1: reset / idle
        // -------------------------------------------------------------------
        $display("[TEST 1] Reset/idle state");
        if (out_valid !== 1'b0)
            report_error("out_valid_o should be low after reset");

        // -------------------------------------------------------------------
        // TEST 2: directed golden vectors, all operations, output always ready
        // -------------------------------------------------------------------
        $display("[TEST 2] Directed golden vectors for all %0d operations", FPU_NUM_OPS);
        out_ready = 1'b1;
        for (int unsigned o = 0; o < FPU_NUM_OPS; o++)
            for (int unsigned tx = 0; tx < FPU_VEC_N; tx++)
                issue(o, tx, 1'b0);
        drain(4 * FPU_VEC_N * FPU_NUM_OPS + 128);
        $display("  sent=%0d received=%0d", n_sent, n_recv);

        // -------------------------------------------------------------------
        // TEST 3: output back-pressure (out_ready_i toggled while stalled)
        // -------------------------------------------------------------------
        $display("[TEST 3] Output back-pressure");
        out_ready = 1'b1;
        for (int unsigned o = 0; o < FPU_NUM_OPS; o++)
            for (int unsigned tx = 0; tx < FPU_VEC_N; tx++)
                issue(o, tx, 1'b1);
        drain(8 * FPU_VEC_N * FPU_NUM_OPS + 256);

        // -------------------------------------------------------------------
        // TEST 4: randomized op mix with random out_ready_i
        // -------------------------------------------------------------------
        $display("[TEST 4] Randomized op mix");
        for (int n = 0; n < 40; n++) begin
            rand_op = $urandom_range(0, FPU_NUM_OPS - 1);
            out_ready = (($urandom_range(0, 3)) != 0);
            issue(rand_op, $urandom_range(0, FPU_VEC_N - 1), 1'b1);
        end
        drain(2048);

        if (n_recv != n_sent)
            report_error($sformatf("beat count mismatch: sent=%0d received=%0d", n_sent, n_recv));

        // -------------------------------------------------------------------
        // TEST 5: IEEE special values with hard-coded result + status
        // status_t = {NV, DZ, OF, UF, NX}
        // -------------------------------------------------------------------
        $display("[TEST 5] IEEE special values (result + status)");
        out_ready = 1'b1;
        special("FDIV 1/0 -> +inf, DZ",    3, 32'h3F800000, 32'h00000000, 32'h00000000, 32'h7F800000, 5'b01000);
        special("FDIV 0/0 -> NaN, NV",     3, 32'h00000000, 32'h00000000, 32'h00000000, 32'h7FC00000, 5'b10000);
        special("FSQRT -4 -> NaN, NV",     4, 32'hC0800000, 32'h00000000, 32'h00000000, 32'h7FC00000, 5'b10000);
        special("FADD inf-inf -> NaN, NV", 0, 32'h7F800000, 32'hFF800000, 32'h00000000, 32'h7FC00000, 5'b10000);
        special("FADD 1+2 -> 3 exact",     0, 32'h3F800000, 32'h40000000, 32'h00000000, 32'h40400000, 5'b00000);
        special("FMUL 2*3 -> 6 exact",     2, 32'h40000000, 32'h40400000, 32'h00000000, 32'h40C00000, 5'b00000);
        special("FSUB 1-1 -> +0 exact",    1, 32'h3F800000, 32'h3F800000, 32'h00000000, 32'h00000000, 5'b00000);
        drain(64);

        // -------------------------------------------------------------------
        // Summary
        // -------------------------------------------------------------------
        out_ready = 1'b0;
        in_valid = 1'b0;
        repeat (4) @(posedge clk);
        $display("");
        $display("=========================================");
        $display(" tb_fpnew_wrapper summary");
        $display("   transactions issued : %0d", n_sent);
        $display("   output beats checked: %0d", n_recv);
        $display("   errors              : %0d", n_errors);
        if (n_errors == 0)
            $display("   RESULT              : PASS");
        else
            $display("   RESULT              : FAIL");
        $display("=========================================");
        if (n_errors != 0)
            $fatal(1, "tb_fpnew_wrapper: %0d error(s)", n_errors);
        $finish;
    end

    // One transaction with all lanes set to the same special operands, checking
    // both the result vector and the per-lane status flags.
    task automatic special(input string name, input int unsigned op,
                           input logic [31:0] a, input logic [31:0] b, input logic [31:0] c,
                           input logic [31:0] exp_lane, input fpnew_pkg::status_t exp_stat);
        drive(make_instr(op), {N_THREADS{a}}, {N_THREADS{b}}, {N_THREADS{c}},
              {N_THREADS{exp_lane}}, 1'b1, exp_stat, 1'b0);
        $display("  %s", name);
    endtask

endmodule

`default_nettype wire
